server:
  port: 9001

spring:
  application:
  ##  中间只能是横杠，不能使用下划线
    name: blog-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.94.10.48:3306/tensquare_base?characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
  rabbitmq:
    host: 192.168.1.109
    port: 5672
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka
  instance:
    prefer-ip-address: true
